spring.application.name=hitandblow
# server.servlet.context-path=/hitandblow
spring.messages.basename=messages
server.servlet.context-path=/
logging.level.com.mycompany.websearchzip.SearchZipController=DEBUG
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:test.db
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.maximumPoolSize=10
